// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtfXCFl-w8zR-d-6e1zWtDaocOEiNlpgA',
    appId: '1:1059137751648:web:52eb0c43e17cd0ba339105',
    messagingSenderId: '1059137751648',
    projectId: 'carier-bridge',
    authDomain: 'carier-bridge.firebaseapp.com',
    storageBucket: 'carier-bridge.firebasestorage.app',
    measurementId: 'G-1VQEC70MZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDE1ae7AbPlcerLSqRsleWbA4WPecc_7s',
    appId: '1:1059137751648:android:0b74883cadea3617339105',
    messagingSenderId: '1059137751648',
    projectId: 'carier-bridge',
    storageBucket: 'carier-bridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsPJ7_dwZEWPwO9JSVflyl5zxNUGDTIwQ',
    appId: '1:1059137751648:ios:5d7bc1e1aed74952339105',
    messagingSenderId: '1059137751648',
    projectId: 'carier-bridge',
    storageBucket: 'carier-bridge.firebasestorage.app',
    iosBundleId: 'com.example.android',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsPJ7_dwZEWPwO9JSVflyl5zxNUGDTIwQ',
    appId: '1:1059137751648:ios:5d7bc1e1aed74952339105',
    messagingSenderId: '1059137751648',
    projectId: 'carier-bridge',
    storageBucket: 'carier-bridge.firebasestorage.app',
    iosBundleId: 'com.example.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtfXCFl-w8zR-d-6e1zWtDaocOEiNlpgA',
    appId: '1:1059137751648:web:3f77cfb46e80299b339105',
    messagingSenderId: '1059137751648',
    projectId: 'carier-bridge',
    authDomain: 'carier-bridge.firebaseapp.com',
    storageBucket: 'carier-bridge.firebasestorage.app',
    measurementId: 'G-S64E1ECXH3',
  );
}
